# application config
server:
  port: ${SERVER_PORT:8083}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/auth/query/api}

# spring config
spring:
  application:
    name: ${APPLICATION_NAME:2f9cd22b217c655c48e732727a91aa7802e65697a4f784095b33229f687e309a}

  # mongo config
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/AuthQueryService}
      database: ${MONGODB_DATABASE:AuthQueryService}

  # rabbitmq config
  rabbitmq:
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:/}
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    ignoreDeclarationException: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION:true}
    concurrentConsumers: ${RABBITMQ_CONCURRENT_CONSUMERS:3}
    maxConcurrentConsumers: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS:10}
    receiveTimeout: ${RABBITMQ_RECEIVE_TIMEOUT:100000}

# security config
security:
  jwt:
    tokenGeneration: ${JWT_TOKEN_GENERATION:https://keycloak-habolabu-nguyentrungkien01.cloud.okteto.net/auth/realms/Habolabu/protocol/openid-connect/token}
    tokenRefresh: ${JWT_TOKEN_REFRESH:https://keycloak-habolabu-nguyentrungkien01.cloud.okteto.net/auth/realms/Habolabu/protocol/openid-connect/token}
    clientId: ${JWT_CLIENT_ID:habolabu-back-end-service}
    clientSecret: ${JWT_CLIENT_SECRET:Lo4PmPoTWYMT6BmzF1f2ir6dlkJ9RiTq}
    grantTypeGenerate: ${JWT_GRANT_TYPE_GENERATE:password}
    grantTypeRefresh: ${JWT_GRANT_TYPE_REFRESH:refresh_token}
    audience: ${JWT_AUDIENCE:account}
    authorizedParties: ${JWT_AUTHORIZED_PARTIES:habolabu-back-end-service}
    issuer: ${JWT_ISSUER:https://keycloak-habolabu-nguyentrungkien01.cloud.okteto.net/auth/realms/Habolabu}

# log config
logging:
  level:
    root: debug
    org.springframework.data.mongodb.core.MongoTemplate: debug