version: "1.0"

volumes:
  auth_query_data:
  auth_query_gradle_data:

networks:
  api_gateway_net:
    external: true
  query_database_net:
    external: true
  rabbitmq_net:
    external: true

services:
  auth_query_service:
    container_name: "auth-query-service"
    build:
      dockerfile: ./docker/Dockerfile
      context: ..
    ports:
      - ${AUTH_QUERY_HOST_PORT}:${AUTH_QUERY_CONTAINER_PORT}
    volumes:
      - auth_query_data:${AUTH_QUERY_SERVICE_VOLUMES}
      - auth_query_gradle_data:${AUTH_QUERY_GRADLE_VOLUMES}
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - api_gateway_net
      - query_database_net
      - rabbitmq_net
    environment:
      SERVER_PORT: ${SERVER_PORT}
      SERVER_CONTEXT_PATH: ${SERVER_CONTEXT_PATH}
      APPLICATION_NAME: ${APPLICATION_NAME}
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_VIRTUAL_HOST: ${RABBITMQ_VIRTUAL_HOST}
      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_IGNORE_DECLARATION_EXCEPTION: ${RABBITMQ_IGNORE_DECLARATION_EXCEPTION}
      RABBITMQ_CONCURRENT_CONSUMERS: ${RABBITMQ_CONCURRENT_CONSUMERS}
      RABBITMQ_MAX_CONCURRENT_CONSUMERS: ${RABBITMQ_MAX_CONCURRENT_CONSUMERS}
      RABBITMQ_RECEIVE_TIMEOUT: ${RABBITMQ_RECEIVE_TIMEOUT}
      JWT_TOKEN_GENERATION: ${JWT_TOKEN_GENERATION}
      JWT_TOKEN_REFRESH: ${JWT_TOKEN_REFRESH}
      JWT_CLIENT_ID: ${JWT_CLIENT_ID}
      JWT_CLIENT_SECRET: ${JWT_CLIENT_SECRET}
      JWT_GRANT_TYPE_GENERATE: ${JWT_GRANT_TYPE_GENERATE}
      JWT_GRANT_TYPE_REFRESH: ${JWT_GRANT_TYPE_REFRESH}
      JWT_AUDIENCE: ${JWT_AUDIENCE}
      JWT_AUTHORIZED_PARTIES: ${JWT_AUTHORIZED_PARTIES}
      JWT_ISSUER: ${JWT_ISSUER}